#Settings and Constants
# ALL config values for the mario platform game

SCREEN_WIDTH = 1024
SCRREEN_HEIGHT = 768
SCREEN_TITLE = "Mario-Style Platformer"
FPS = 60

GRAVITY = 0.8
PLAYER_JUMP_SPEED = -16
PLAYER_MOVEMENT_SPEED = 5
TERMINAL_VELOCITY = 20

TILE_SIZE = 32
TILE_SCALING = 1.0

PLAYER_START_X = 100
PLAYER_START_Y = 200
PLAYER_LIVES = 3
PLAYER_SIZE = 32

ENEMY_SPEED = 1
ENEMY_BOUNCE_BACK = True

COIN_VALUE = 100
COIN_SIZE = 24

CAMERA_SPEED = 5
LEVEL_END_X = 3000

JUMP_KEY = "SPACE"
LEFT_KEY = "LEFT"
RIGHT_KEY = "RIGHT"
PAUSE_KEY = "P"
